# Generated by Django 2.2.9 on 2020-01-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0002_auto_20191222_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalgroup',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='musicalgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curiosity.MusicalGroup'),
        ),
    ]
