# Generated by Django 2.2.9 on 2019-12-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('record_company', models.CharField(max_length=25)),
                ('release_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('birth_date', models.DateTimeField(null=True)),
                ('instrument', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('style', models.CharField(max_length=20)),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curiosity.Album')),
                ('musicians', models.ManyToManyField(to='curiosity.Musician')),
            ],
        ),
    ]
